"""Markdown export format."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TextIO

from flowfeed.i18n import t
from flowfeed.sources.base import NewsItem


class MarkdownExporter:
    """Export news items to Markdown format."""

    def export(
        self,
        items: list[NewsItem],
        output: str | Path | TextIO | None = None,
        title: str = "",
    ) -> str:
        """Export items as Markdown string, optionally write to file."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        md_title = title or t("md.title")
        lines = [
            f"# {md_title}",
            "",
            f"> {t('md.generated', time=now, n=len(items))}",
            "",
            "---",
            "",
        ]

        # Group by source
        by_source: dict[str, list[NewsItem]] = {}
        for item in items:
            by_source.setdefault(item.source_name, []).append(item)

        for source_name, source_items in by_source.items():
            lines.append(f"## 📡 {source_name}")
            lines.append("")
            for item in source_items:
                score = f" (🔥 {item.hot_score:.0f})" if item.hot_score > 0 else ""
                summary = f" — {item.summary}" if item.summary else ""
                lines.append(f"**{item.rank}.** [{item.title}]({item.url}){score}{summary}")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by [FlowFeed](https://github.com/gitstq/flowfeed)*")

        result = "\n".join(lines)

        if output is not None:
            if isinstance(output, (str, Path)):
                Path(output).parent.mkdir(parents=True, exist_ok=True)
                Path(output).write_text(result, encoding="utf-8")
            else:
                output.write(result)

        return result
