"""FlowFeed Internationalization (i18n) module.

Supports three locales: en (English), zh-CN (简体中文), zh-TW (繁體中文).

Priority:
  1. Explicit lang parameter (CLI --lang / function argument)
  2. FLOWFEED_LANG environment variable
  3. language field in config.yaml
  4. System locale detection (LANG / LC_ALL / LANGUAGE)
  5. Fallback to "en"
"""

from __future__ import annotations

import locale
import os
from typing import Any

# ---------- language pack ----------

_TRANSLATIONS: dict[str, dict[str, str]] = {
    # ---- English ----
    "en": {
        # CLI main
        "cli.description": "FlowFeed — Lightweight Intelligent News Aggregation Engine",
        "cli.no_items": "No items found. Try different filters or sources.",
        "cli.interrupted": "Interrupted by user.",
        # CLI list-sources
        "cli.list_sources.title": "Available Sources",
        "cli.list_sources.total": "Total: {n} sources",
        "cli.list_sources.col_id": "ID",
        "cli.list_sources.col_name": "Name",
        "cli.list_sources.col_category": "Category",
        "cli.list_sources.col_description": "Description",
        # CLI init-config
        "cli.init_config.exists": "Config file already exists at {path}. Overwrite?",
        "cli.init_config.cancelled": "Cancelled.",
        "cli.init_config.written": "Example config written to {path}",
        "cli.init_config.hint": "Edit the file to customize your sources and filters.",
        # CLI sources
        "cli.sources.unavailable": "Unavailable",
        # Engine summary
        "engine.fetch_completed": "Fetch completed in {dur:.2f}s",
        "engine.total_fetched": "Total fetched: {n}",
        "engine.after_dedup": "After dedup:   {n}",
        "engine.after_filter": "After filter:  {n}",
        "engine.sources_ok_fail": "Sources:       {ok} successful, {fail} failed",
        "engine.failed_sources": "Failed sources:",
        "engine.no_enabled_sources": "No enabled sources found. Check your config.",
        "engine.unknown_source": "Unknown source: {id}",
        "engine.init_source_failed": "Failed to init source {id}: {err}",
        "engine.fetching_from": "Fetching from {name}...",
        "engine.fetch_ok": "{name}: {n} items",
        # Terminal exporter
        "term.no_items": "No items to display.",
        "term.header": "FlowFeed — {items} items from {sources} sources",
        "term.header_sub": "Sorted by composite hot score",
        "term.top_stories": "Top Stories",
        "term.col_rank": "#",
        "term.col_score": "Score",
        "term.col_title": "Title",
        "term.col_source": "Source",
        "term.col_category": "Category",
        "term.source_summary": "Source Summary",
        "term.source_col_source": "Source",
        "term.source_col_items": "Items",
        # Export messages
        "export.to_json": "Exported {n} items to JSON",
        "export.to_markdown": "Exported {n} items to Markdown",
        "export.to_html": "Exported {n} items to HTML dashboard",
        "export.to_rss": "Exported {n} items to RSS feed",
        # HTML dashboard
        "html.lang": "en",
        "html.stat_total": "Total Items",
        "html.stat_sources": "Sources",
        "html.stat_top_score": "Top Score",
        "html.meta": "{time} | {items} items from {sources} sources",
        "html.footer": "Powered by FlowFeed — Lightweight News Aggregation Engine",
        # Markdown
        "md.title": "FlowFeed Daily Digest",
        "md.generated": "Generated by FlowFeed at {time} | {n} items",
        # RSS
        "rss.title": "FlowFeed — Aggregated News Feed",
        "rss.description": "Real-time aggregated news from multiple sources",
        "rss.language": "en",
        # Config
        "config.load_failed": "Failed to load config from {path}: {err}",
    },
    # ---- 简体中文 ----
    "zh-CN": {
        "cli.description": "FlowFeed — 轻量智能新闻聚合引擎",
        "cli.no_items": "未找到任何内容，请尝试更换筛选条件或数据源。",
        "cli.interrupted": "用户中断。",
        "cli.list_sources.title": "可用数据源",
        "cli.list_sources.total": "共 {n} 个数据源",
        "cli.list_sources.col_id": "ID",
        "cli.list_sources.col_name": "名称",
        "cli.list_sources.col_category": "分类",
        "cli.list_sources.col_description": "描述",
        "cli.init_config.exists": "配置文件已存在于 {path}，是否覆盖？",
        "cli.init_config.cancelled": "已取消。",
        "cli.init_config.written": "示例配置已写入 {path}",
        "cli.init_config.hint": "编辑该文件以自定义数据源和筛选规则。",
        "cli.sources.unavailable": "不可用",
        "engine.fetch_completed": "抓取完成，耗时 {dur:.2f} 秒",
        "engine.total_fetched": "总抓取数：{n}",
        "engine.after_dedup": "去重后：  {n}",
        "engine.after_filter": "筛选后：  {n}",
        "engine.sources_ok_fail": "数据源：  {ok} 个成功，{fail} 个失败",
        "engine.failed_sources": "失败的数据源：",
        "engine.no_enabled_sources": "未找到已启用的数据源，请检查配置。",
        "engine.unknown_source": "未知数据源：{id}",
        "engine.init_source_failed": "初始化数据源 {id} 失败：{err}",
        "engine.fetching_from": "正在从 {name} 抓取...",
        "engine.fetch_ok": "{name}：{n} 条",
        "term.no_items": "没有可展示的内容。",
        "term.header": "FlowFeed — 来自 {sources} 个数据源的 {items} 条内容",
        "term.header_sub": "按综合热度排序",
        "term.top_stories": "热门榜单",
        "term.col_rank": "#",
        "term.col_score": "热度",
        "term.col_title": "标题",
        "term.col_source": "来源",
        "term.col_category": "分类",
        "term.source_summary": "数据源统计",
        "term.source_col_source": "来源",
        "term.source_col_items": "条数",
        "export.to_json": "已导出 {n} 条内容为 JSON",
        "export.to_markdown": "已导出 {n} 条内容为 Markdown",
        "export.to_html": "已导出 {n} 条内容为 HTML 仪表盘",
        "export.to_rss": "已导出 {n} 条内容为 RSS 订阅",
        "html.lang": "zh-CN",
        "html.stat_total": "内容总数",
        "html.stat_sources": "数据源数",
        "html.stat_top_score": "最高热度",
        "html.meta": "{time} | 来自 {sources} 个数据源的 {items} 条内容",
        "html.footer": "由 FlowFeed 驱动 — 轻量智能新闻聚合引擎",
        "md.title": "FlowFeed 每日资讯",
        "md.generated": "由 FlowFeed 生成于 {time} | 共 {n} 条",
        "rss.title": "FlowFeed — 聚合新闻订阅",
        "rss.description": "来自多个数据源的实时聚合新闻",
        "rss.language": "zh-CN",
        "config.load_failed": "加载配置失败 {path}：{err}",
    },
    # ---- 繁體中文 ----
    "zh-TW": {
        "cli.description": "FlowFeed — 輕量智慧新聞聚合引擎",
        "cli.no_items": "未找到任何內容，請嘗試更換篩選條件或資料來源。",
        "cli.interrupted": "使用者中斷。",
        "cli.list_sources.title": "可用資料來源",
        "cli.list_sources.total": "共 {n} 個資料來源",
        "cli.list_sources.col_id": "ID",
        "cli.list_sources.col_name": "名稱",
        "cli.list_sources.col_category": "分類",
        "cli.list_sources.col_description": "描述",
        "cli.init_config.exists": "設定檔已存在於 {path}，是否覆蓋？",
        "cli.init_config.cancelled": "已取消。",
        "cli.init_config.written": "範例設定已寫入 {path}",
        "cli.init_config.hint": "編輯該檔案以自訂資料來源和篩選規則。",
        "cli.sources.unavailable": "不可用",
        "engine.fetch_completed": "抓取完成，耗時 {dur:.2f} 秒",
        "engine.total_fetched": "總抓取數：{n}",
        "engine.after_dedup": "去重後：  {n}",
        "engine.after_filter": "篩選後：  {n}",
        "engine.sources_ok_fail": "資料來源：  {ok} 個成功，{fail} 個失敗",
        "engine.failed_sources": "失敗的資料來源：",
        "engine.no_enabled_sources": "未找到已啟用的資料來源，請檢查設定。",
        "engine.unknown_source": "未知資料來源：{id}",
        "engine.init_source_failed": "初始化資料來源 {id} 失敗：{err}",
        "engine.fetching_from": "正在從 {name} 抓取...",
        "engine.fetch_ok": "{name}：{n} 條",
        "term.no_items": "沒有可展示的內容。",
        "term.header": "FlowFeed — 來自 {sources} 個資料來源的 {items} 條內容",
        "term.header_sub": "按綜合熱度排序",
        "term.top_stories": "熱門榜單",
        "term.col_rank": "#",
        "term.col_score": "熱度",
        "term.col_title": "標題",
        "term.col_source": "來源",
        "term.col_category": "分類",
        "term.source_summary": "資料來源統計",
        "term.source_col_source": "來源",
        "term.source_col_items": "條數",
        "export.to_json": "已匯出 {n} 條內容為 JSON",
        "export.to_markdown": "已匯出 {n} 條內容為 Markdown",
        "export.to_html": "已匯出 {n} 條內容為 HTML 儀表板",
        "export.to_rss": "已匯出 {n} 條內容為 RSS 訂閱",
        "html.lang": "zh-TW",
        "html.stat_total": "內容總數",
        "html.stat_sources": "資料來源數",
        "html.stat_top_score": "最高熱度",
        "html.meta": "{time} | 來自 {sources} 個資料來源的 {items} 條內容",
        "html.footer": "由 FlowFeed 驅動 — 輕量智慧新聞聚合引擎",
        "md.title": "FlowFeed 每日資訊",
        "md.generated": "由 FlowFeed 生成於 {time} | 共 {n} 條",
        "rss.title": "FlowFeed — 聚合新聞訂閱",
        "rss.description": "來自多個資料來源的即時聚合新聞",
        "rss.language": "zh-TW",
        "config.load_failed": "載入設定失敗 {path}：{err}",
    },
}

# Alias: zh → zh-CN
_TRANSLATIONS["zh"] = _TRANSLATIONS["zh-CN"]

SUPPORTED_LOCALES = ["en", "zh-CN", "zh-TW"]

# ---------- active locale state ----------

_active_locale: str = "en"


def detect_locale() -> str:
    """Auto-detect locale from environment."""
    # Check FLOWFEED_LANG env var first
    env_lang = os.environ.get("FLOWFEED_LANG", "").strip()
    if env_lang:
        return _normalize_locale(env_lang)

    # Try system locale
    try:
        sys_locale = locale.getlocale()[0] or ""
        if sys_locale:
            return _normalize_locale(sys_locale)
    except Exception:
        pass

    # Check LANG / LANGUAGE env vars (Unix)
    for var in ("LANG", "LC_ALL", "LANGUAGE"):
        val = os.environ.get(var, "")
        if val:
            return _normalize_locale(val.split(".")[0].split("@")[0])

    return "en"


def _normalize_locale(loc: str) -> str:
    """Normalize a locale string to one of SUPPORTED_LOCALES."""
    loc = loc.strip().replace("_", "-").lower()
    if loc == "zh" or loc.startswith("zh-cn") or loc.startswith("zh_hans") or loc.startswith("zh-hans"):
        return "zh-CN"
    if loc.startswith("zh-tw") or loc.startswith("zh_hant") or loc.startswith("zh-hant") or loc == "zh-hk":
        return "zh-TW"
    if loc.startswith("en"):
        return "en"
    return "en"


def set_locale(loc: str) -> None:
    """Set the active locale. Normalizes the input."""
    global _active_locale
    _active_locale = _normalize_locale(loc)


def get_locale() -> str:
    """Return the current active locale."""
    return _active_locale


def t(key: str, **kwargs: Any) -> str:
    """Translate a key in the active locale.

    Uses Python str.format_map() for placeholder substitution.
    Falls back to English if the key is missing in the active locale.
    """
    pack = _TRANSLATIONS.get(_active_locale, _TRANSLATIONS["en"])
    text = pack.get(key)
    if text is None:
        # Fallback to English
        text = _TRANSLATIONS["en"].get(key, key)
    if kwargs:
        try:
            return text.format_map(kwargs)
        except (KeyError, IndexError):
            return text
    return text
